### ISSUE TITLE
Can't build from source on Mac M1

### ISSUE THREAD

**Issue by weavermedia** [drbourbon/deluge-commander#7]
Following the clone & build instructions, I get a large amount of deprecation errors, an EBADENGINE error and a 404 when trying to install Electron.

MacBook Air M1
macOS Ventura 13.2
Node: v19.5.0
NPM: 9.3.1

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'pkcs7@1.0.2',
npm WARN EBADENGINE   required: { npm: '^1.4.6', node: '^0.10' },
npm WARN EBADENGINE   current: { node: 'v19.5.0', npm: '9.3.1' }
npm WARN EBADENGINE }
```

```
npm ERR! code 1
npm ERR! path /Users/dan/code/deluge-commander/node_modules/electron
npm ERR! command failed
npm ERR! command sh -c node install.js
Downloading electron-v2.0.4-darwin-arm64.zip
npm ERR! Error: GET https://github.com/electron/electron/releases/download/v2.0.4/electron-v2.0.4-darwin-arm64.zip returned 404
npm ERR! /Users/dan/code/deluge-commander/node_modules/electron/install.js:47
npm ERR!   throw err
npm ERR!   ^
npm ERR! 
npm ERR! Error: Failed to find Electron v2.0.4 for darwin-arm64 at https://github.com/electron/electron/releases/download/v2.0.4/electron-v2.0.4-darwin-arm64.zip
npm ERR!     at Request.<anonymous> (/Users/dan/code/deluge-commander/node_modules/nugget/index.js:197:61)
npm ERR!     at Request.emit (node:events:512:28)
npm ERR!     at Request.onRequestResponse (/Users/dan/code/deluge-commander/node_modules/request/request.js:1059:10)
npm ERR!     at ClientRequest.emit (node:events:512:28)
npm ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:694:27)
npm ERR!     at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
npm ERR!     at TLSSocket.socketOnData (node:_http_client:536:22)
npm ERR!     at TLSSocket.emit (node:events:512:28)
npm ERR!     at addChunk (node:internal/streams/readable:324:12)
npm ERR!     at readableAddChunk (node:internal/streams/readable:297:9)
npm ERR! 
npm ERR! Node.js v19.5.0
```

**Comment by drbourbon** [comment]
Just committed an updated package.json to build on newer electron framework. heavily untested

**Comment by weavermedia** [comment]
Thanks for the commit but I still get a 404 trying to install Electron v8.2.0-darwin-arm64.

Digging into this it looks like Electron didn't add support for Mac arm64 until 11.0.

https://www.electronjs.org/blog/apple-silicon
